config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # Incluir aqui verificação se user é administrador
  # para montar o painel do sidekiq
  if Rails.env.development?
    mount Sidekiq::Web => '/sidekiq'
  end
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'pages#home'

  resources :campaigns, except: [:new] do
    post 'raffle', on: :member # --> /campaigns/:id/raffle
    # post 'raffle', on: :collection # -->  /campaigns/raffle
  end

  resources :members, only: [:create, :destroy, :update]

  # Nesta rota não passo :id, passo o token, por isso
  # não está no resources members.
  get 'members/:token/opened', to: 'members#opened'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :user
  has_many :members, dependent: :destroy

  before_validation :set_member, on: :create
  before_validation :set_status, on: :create

  enum status: [:pending, :finished]
  validates :title, :description, :user, :status, presence: true

  def count_opened
    self.members.where(open: true).count
  end

  private

  def set_status
    self.status = :pending
  end

  # Quem está criando a campaign também é membro desta
  def set_member
    self.members << Member.create(name: self.user.name, email: self.user.email)
  end
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :campaign
  validates  :name, :campaign, presence: true
  after_destroy :set_campaign_pending

  def set_pixel
    self.open  = false
    # Gera um token enquanto ele seja único ou seja não exista
    self.token = loop do
      random_token = SecureRandom.urlsafe_base64(nil, false)
      break random_token if not Member.exists?(token: random_token)
    end
    self.save!
  end

  protected

  # Sempre que um membro é adicionando a uma campaign, a mesma é atualizada para status pending
  def set_campaign_pending
    self.campaign.update(status: :pending)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :campaigns, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from ActiveRecord::RecordNotFound, :with => :render_404

  def render_404
    redirect_to main_app.root_url
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_campaign, only: [:show, :destroy, :update, :raffle]
  before_action :is_owner?, only: [:show, :destroy, :update, :raffle]

  def show
  end

  def index
    @campaigns = current_user.campaigns
  end

  def create
    @campaign = Campaign.new(user: current_user, title: 'Título da Campanha', description: 'Descrição da campanha')

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to "/campaigns/#{@campaign.id}" }
      else
        format.html { redirect_to main_app.root_url, notice: @campaign.errors }
      end
    end
  end

  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.json { render json: true }
      else
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @campaign.destroy

    respond_to do |format|
      format.json { render json: true }
    end
  end

  def raffle
    respond_to do |format|
      if @campaign.status != 'pending'
        format.json { render json: 'Já foi sorteada', status: :unprocessable_entity }
      elsif @campaign.members.count < 3
        format.json { render json: 'A campanha precisa de pelo menos 3 pessoas', status: :unprocessable_entity }
      else
        CampaignRaffleJob.perform_later @campaing
        format.json { render json: true }
      end
    end
  end

  private

  def set_campaign
    @campaign = Campaign.find(params[:id])
  end

  def campaign_params
    params.require(:campaign).permit(:title, :description, :event_date, :event_hour, :location).merge(user: current_user)
  end

  def is_owner?
    unless current_user == @campaign.user
      respond_to do |format|
        format.json { render json: false, status: :forbidden }
        format.html { redirect_to main_app.root_url }
      end
    end
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_user!, except: [:opened]

  before_action :set_member, only: [:show, :destroy, :update]
  before_action :is_owner?, only: [:destroy, :update]
  before_action :set_member_by_token, only: [:opened]

  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.json { render json: @member }
      else
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @member.destroy

    respond_to do |format|
      format.json { render json: true }
    end
  end

  def update
    respond_to do |format|
      if @member.update(member_params)
        format.json { render json: true }
      else
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  def opened
    @member.update(open: true)
    gif = Base64.decode64("R0lGODlhAQABAPAAAAAAAAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==")
    render text: gif, type: 'image/gif'
  end

  private

  def set_member
    @member = Member.find(params[:id])
  end

  def set_member_by_token
    @member = Member.find_by!(token: params[:token])
  end

  def member_params
    params.require(:member).permit(:name, :email, :campaign_id)
  end

  def is_owner?
    unless current_user == @member.campaign.user
      respond_to do |format|
        format.json { render json: false, status: :forbidden }
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).premit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
  def open_number(campaign)
    "#{campaign.count_opened}/#{campaign.members.count}"
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/campaigns/index.html.haml
.row.campaigns
  .col.s8.offset-s2
    %p.title Campanhas
  .row.cards
    .col.s8.offset-s2
      - @campaigns.each do |c|
        .card.horizontal
          .card-content.col.s12
            .col.s12.l8.m12
              .row
                .col.s8.m9.l9
                  %p.title= truncate(c.title, length: 30, omission: '...')
                .col.s4.m2.l2
                  %p.data= (c.event_date)? c.event_date.strftime("%d/%m/%y") : ''
              .row
                .col.s12.m12.l12
                  %p.subtitle= truncate(c.description, length: 70, omission: '...')
              .row.status
                .col.s6.m6.l4.visibility
                  %i.material-icons.visibility-icon visibility
                  %span.visibility-text
                    Vistos #{open_number(c)}
                .col.s2.m2.offset-s4.l2.offset-l6
                  %span{:class => "new badge #{(c.status == "pending")? 'orange' : ''}"}
                    = (c.status == "pending")? 'Pendente' : 'Sorteado'
            .col.l4.s12.m12.center.enter
              .row
                .col.s12
                  = link_to 'Entrar', campaign_path(c), class: 'waves-effect waves-light btn grey'
  .fixed-action-btn.campaigns-btn
    = form_tag("/campaigns", method: "post") do
      %button.btn-floating.btn-large.red.pulse{:type => "submit"}
        %i.large.material-icons add

app/views/campaigns/show.html.haml
.row.campaigns
  .col.s8.offset-s2
    %p.title Informações
  .campaign
    .row.cards
      .col.s8.offset-s2
        .card.horizontal
          .card-content.col.s12
            = form_for @campaign, url: {action: "update"}, html: {class: "col s12 update_campaign"} do |f|
              .row
                .row
                  .col.s12.l4.input-field
                    = f.text_field :title, 'data-length': "20"
                    %label{:class => "#{(@campaign.title)? 'active' : ''}", :for => "title"} Título
                  .col.s12.l3.input-field
                    = f.date_field :event_date, class: 'datepicker'
                    %label{:class => "#{(@campaign.event_date)? 'active' : ''}", :for => "title"} Data
                  .col.s12.l2.input-field
                    = f.text_field :event_hour
                    %label{:class => "#{(@campaign.event_hour)? 'active' : ''}", :for => "title"} Hora
                  .col.s12.l3.input-field
                    = f.text_field :location, 'data-length': "20"
                    %label{:class => "#{(@campaign.location)? 'active' : ''}", :for => "title"} Local
                .row
                  .col.s12.input-field
                    = f.text_field :description, 'data-length': "150"
                    %label{:class => "#{(@campaign.description)? 'active' : ''}", :for => "title"} Descrição
    .col.s8.offset-s2
      %p.title Membros
    .row.cards.members
      .col.s8.offset-s2
        .card.horizontal
          .card-content.col.s12
            .member_list
              - @campaign.members.each do |m|
                .member{:id => "member_#{m.id}"}
                  .row
                    .col.s12.m5.input-field
                      %input#name.validate{:type => "text", :value => "#{m.name}"}/
                      %label.active{:for => "name"} Nome
                    .col.s12.m5.input-field
                      %input#email.validate{:type => "email", :value => "#{m.email}"}/
                      %label.active{"data-error" => "Formato incorreto", :for => "email"} Email
                    .col.s3.offset-s3.m1.input-field
                      %i{:class => "material-icons icon #{(m.open)? 'opened' : ''}"} visibility
                    .col.s3.m1.input-field
                      %a.remove_member{:href => "#", :id => "#{m.id}"}
                        %i.material-icons.icon delete
            = form_for(Member.new) do |f|
              .member
                .row
                  = f.hidden_field :campaign_id, value: @campaign.id
                  .col.s12.m5.input-field
                    = f.text_field :name, class: "validate"
                    %label.active{:for => "name"} Nome
                  .col.s12.m5.input-field
                    = f.email_field :email, class: "validate"
                    %label.active{"data-error" => "Formato incorreto", :for => "member[email]"} Email
    .row.btn-actions
      .col.s12.center
        .col.s6.m3.offset-m3.l2.offset-l4
          = form_for @campaign, method: 'delete', html: {class: 'remove_campaign'} do |f|
            %button.waves-effect.waves-light.btn.grey{:type => "submit"} Remover
        .col.s6.m3.l3
          = form_tag(raffle_campaign_path(@campaign), method: 'post', class: 'raffle_campaign') do
            %button.waves-effect.waves-light.btn.red{:type => "submit"} Sortear e enviar

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title Amigo Secreto
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header 
      = render 'shared/navbar'
    
    %main 
      .container
        = yield

    %footer
      = render 'shared/footer'

app/views/pages/home.html.haml
.row.home
  .center
    %h4.title Surpreenda no Amigo Secreto
    %h5.subtitle Crie a sua brincadeira apenas com o nome e email dos seus amigos
    %h5.subtitle2
      Rápido, fácil e garantido
      %i.material-icons.home-icon favorite
    = form_tag("/campaigns", method: "post") do
      = submit_tag("Criar Agora", class: "waves-effect waves-light btn home-button")

app/views/shared/_footer.html.haml
.page-footer
  .container
    .copyright
      %b
        Criando com
        %i.material-icons.copyright-icon favorite
        no
        %a.copyright-link{:href => "http://onebitcode.com/bootcamp-one-bit-code/"} Bootcamp OneBitCode

app/views/shared/_navbar.html.haml
.navbar-fixed
  %nav.top-nav
    .nav-wrapper.col.s12
      %a.brand-logo{:href => "/"}
        = image_tag("logo.png", class: "logo-img")
        %span.logo-title
          Nosso Amigo Secreto
      %a.button-collapse{"data-activates" => "side-bar", :href => "#"}
        %i.material-icons menu
      %ul.right.hide-on-med-and-down
        - if current_user
          %li
            %a{:href => "/campaigns"} Campanhas
          %li
            %a{:href => "/users/edit"} Perfil
          %li
            = link_to('Sair', destroy_user_session_path, :method => :delete)
        - else
          %li
            %a{:href => "/users/sign_in"} Entrar
          %li
            %a{:href => "/users/sign_up"} Criar Conta
            
%ul#side-bar.side-nav
  - if current_user
    %li
      %a{:href => "/campaigns"} Campanhas
    %li
      %a{:href => "/users/edit"} Perfil
    %li
      .divider
    %li
      = link_to('Sair', destroy_user_session_path, :method => :delete)
  - else
    %li
      %a{:href => "/users/sign_in"} Entrar
    %li
      .divider
    %li
      %a{:href => "/users/sign_up"} Criar Conta
    %li
      .divider